// src/index.js
require("dotenv").config();

process.env.FFMPEG_PATH = require("ffmpeg-static");

const dns = require("node:dns");
dns.setDefaultResultOrder("ipv4first");

const { Client, GatewayIntentBits, Partials } = require("discord.js");
const { Player, QueryType, useMainPlayer } = require("discord-player");
const { YoutubeiExtractor } = require("discord-player-youtubei");
const {
  SpotifyExtractor,
  AppleMusicExtractor,
  SoundCloudExtractor,
} = require("@discord-player/extractor");
const { startKeepAlive } = require("./utils/keepAlive");
const { registerPlayerEvents } = require("./events/playerEvents");
const readyEvent = require("./events/ready");
const messageCreateEvent = require("./events/messageCreate");

// ─── Discord Client ───────────────────────────────────────────────────────────
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildVoiceStates,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
  partials: [Partials.Channel],
});

// ─── Player ───────────────────────────────────────────────────────────────────
const player = new Player(client, { skipOnNoStream: false });

// ─── Spotify / Apple Music bridge ────────────────────────────────────────────
// SpotifyExtractor has no audio — it fetches metadata then needs a bridge to
// find audio on YouTube. We do the search ourselves and return the YT URL.
// YoutubeiExtractor then streams that YT URL (authenticated, no deciphering needed).
async function bridgeViaYoutubei(extractor, track) {
  const query = `${track.title} ${track.author}`.trim();
  try {
    const p = useMainPlayer();
    const result = await p.search(query, {
      searchEngine: QueryType.YOUTUBE_SEARCH,
    });
    if (!result || result.tracks.length === 0)
      throw new Error(`No YT results for: ${query}`);
    return result.tracks[0].url;
  } catch (err) {
    console.error(`[Bridge] "${query}": ${err.message}`);
    throw err;
  }
}

// ─── Extractors ───────────────────────────────────────────────────────────────
async function initExtractors() {
  // YOUTUBE_OAUTH_TOKEN must be the semicolon-separated STRING generated by
  // generate-token.js — NOT a JSON object.
  // Format: "access_token=ya29.xxx; refresh_token=1//xxx; token_type=Bearer; expiry_date=xxx"
  //
  // If the env var is set, use WEB client with OAuth (bypasses Render IP block fully).
  // If not set, fall back to IOS client (may work if YouTube doesn't block the IP).
  const oauthToken = process.env.YOUTUBE_OAUTH_TOKEN;

  const youtubeiOptions = oauthToken
    ? {
        authentication: oauthToken, // MUST be the string, not an object
        streamOptions: { useClient: "WEB" },
        logLevel: "NONE",
      }
    : {
        streamOptions: { useClient: "IOS" },
      };

  await player.extractors.register(YoutubeiExtractor, youtubeiOptions);
  console.log(
    oauthToken
      ? "✅ YoutubeiExtractor loaded (WEB + OAuth — full Render support)"
      : "✅ YoutubeiExtractor loaded (IOS — no OAuth set)",
  );

  await player.extractors.register(SpotifyExtractor, {
    clientId: process.env.SPOTIFY_CLIENT_ID,
    clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
    createStream: bridgeViaYoutubei,
  });
  console.log("✅ SpotifyExtractor loaded");

  await player.extractors.register(AppleMusicExtractor, {
    createStream: bridgeViaYoutubei,
  });
  console.log("✅ AppleMusicExtractor loaded");

  await player.extractors.register(SoundCloudExtractor, {});
  console.log("✅ SoundCloudExtractor loaded");

  await player.extractors.loadDefault(
    (ext) =>
      ext !== "YouTubeExtractor" &&
      ext !== "YoutubeExtractor" &&
      ext !== "SpotifyExtractor" &&
      ext !== "AppleMusicExtractor" &&
      ext !== "SoundCloudExtractor",
  );
  console.log("✅ Remaining extractors loaded");
}

// ─── Boot ─────────────────────────────────────────────────────────────────────
async function boot() {
  try {
    await initExtractors();
  } catch (err) {
    console.error("❌ Extractor init failed:", err.message);
  }

  registerPlayerEvents(player);
  client.player = player;

  client.once("clientReady", (...args) => readyEvent.execute(...args));
  client.on(messageCreateEvent.name, (...args) =>
    messageCreateEvent.execute(...args),
  );
  client.on("error", (err) => console.error("[Discord Error]", err));
  client.on("warn", (warn) => console.warn("[Discord Warn]", warn));

  process.on("unhandledRejection", (reason) =>
    console.error("[Unhandled Rejection]", reason),
  );
  process.on("uncaughtException", (err) =>
    console.error("[Uncaught Exception]", err),
  );

  startKeepAlive();

  const token = process.env.DISCORD_TOKEN;
  if (!token) {
    console.error("DISCORD_TOKEN not set!");
    process.exit(1);
  }

  client.login(token).catch((err) => {
    console.error("Login failed:", err.message);
    process.exit(1);
  });
}

boot();
